#**Laboratorium 2** - ciąg dalszy podstaw języka Python

Drugie zajęcia były kontynuacją nauki podstaw programowania w języku Python. Poniżej znajduje się kod z laboratorium. Po zapoznaniu się z jego działaniem, podobnie jak podczas pierwszych zajęć, należało zrealizować podane przez prowadzącego zadanie. Jego rozwiązanie widoczne jest na dole notatnika.

In [ ]:
import numpy as np

In [ ]:
a_list= [1,2,3,4,5, [1,2,3], "temat"] # nie idealna lista
k_krotka = (1,2,3,4,5, [1,2,3], "temat")
b_list = [1,2,3,4,5]
n_array = np.array(b_list) # wektor numpy


In [ ]:
a_list+b_list
n_array+n_array

array([ 2,  4,  6,  8, 10])

In [ ]:
a_list[3]

4

In [ ]:
a_list.append(100)
print(a_list)

[1, 2, 3, 4, 5, [1, 2, 3], 'temat', 100]


In [ ]:
k_krotka[4]

5

In [ ]:
k_krotka.append(100)

In [ ]:
np.array(b_list)+np.array(b_list)

array([ 2,  4,  6,  8, 10])

In [ ]:
n_array = np.array(a_list) # wektor numpy

In [ ]:
n_array

array([1, 2, 3, 4, 5, list([1, 2, 3]), 'temat', 100], dtype=object)

In [ ]:
#### Nowosci

studenci_slownik = {123: 123,"Igor":3, "Frankek":5, "Zosia":22,"Julia":[2,21], (1,2):"Krotka"}

In [ ]:
print(studenci_slownik)

{123: 123, 'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], (1, 2): 'Krotka'}


In [ ]:
studenci_slownik["Zosia"]

22

In [ ]:
for elementy in studenci_slownik:
    print(elementy)

print("*"*20)
for elementy in studenci_slownik.keys():
    print(elementy)

123
Igor
Frankek
Zosia
Julia
(1, 2)
********************
123
Igor
Frankek
Zosia
Julia
(1, 2)


In [ ]:
for elementy in studenci_slownik.items():
    print(elementy)

(123, 123)
('Igor', 3)
('Frankek', 5)
('Zosia', 22)
('Julia', [2, 21])
((1, 2), 'Krotka')


In [ ]:
for elementy in studenci_slownik.values():
    print(elementy)

123
3
5
22
[2, 21]
Krotka


In [ ]:
studenci_slownik["Cuthulu"]= -1000000

In [ ]:
studenci_slownik

{(1, 2): 'Krotka',
 123: 123,
 'Cuthulu': -1000000,
 'Frankek': 5,
 'Igor': 3,
 'Julia': [2, 21],
 'Zosia': 22}

In [ ]:
automatyczna_lista=[liczba**2 for liczba in range(100) if liczba%4==0]
print(automatyczna_lista)

[0, 16, 64, 144, 256, 400, 576, 784, 1024, 1296, 1600, 1936, 2304, 2704, 3136, 3600, 4096, 4624, 5184, 5776, 6400, 7056, 7744, 8464, 9216]


In [ ]:
studenci = studenci_slownik.keys()
automatyczny_slownik=dict(para for para in enumerate(studenci))
print(automatyczny_slownik)

{0: 123, 1: 'Igor', 2: 'Frankek', 3: 'Zosia', 4: 'Julia', 5: (1, 2), 6: 'Cuthulu'}


In [ ]:
##### zbiory

a={1,2,3,"Franek"}
b={2,3,4,"Franek"}


In [ ]:
a|b #suma zbiorów, sum of sets

In [ ]:
a.add("Franek")
print(a)

In [ ]:
1 in a
"Igor" in studenci_slownik

### Własne typy

In [ ]:
zajecia = [["wf"],
           ["informatyka", "nauka czytania"],
           ["relax", "jedzenie"],
           ["mispy","mispy w domu"],
           ["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"]
          ]

dnityg= ["Pon","Wto","Sro","Czwar","Pio"]

def dodaj_dwie_liczby(liczba1,liczba2):
    return liczba1+liczba2

In [ ]:
class DzienZajec():
    """obiekt trzymający dany dzień zajęć i przypisane mu metody"""
    
    
    def __init__(self, lista_na_dany_dzien, nazwa_dnia): #definicja
        self.lista_zajec= lista_na_dany_dzien
        self.dzien = nazwa_dnia
        

    
    def ile_mispow(self):
        ile_m = sum([1 for zajecie in self.lista_zajec if "misp" in zajecie.lower()])
        return ile_m

    @property #zamienia na wlasciwosc   
    def ile_zajec(self):
        return len(self.lista_zajec)
    
    def __repr__(self):
        zajecia_do_stringa = ", ".join(self.lista_zajec)
        return "W dzien {} mam zajecia: {}".format(self.dzien, zajecia_do_stringa)
    

In [ ]:
pio_zajecia = DzienZajec(["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"],
                        "piatek")

In [ ]:
pio_zajecia.ile_zajec

In [ ]:
print(pio_zajecia)

In [ ]:
pio_zajecia.lista_zajec

In [ ]:
pio_zajecia.lista_zajec.append("MISP")
print(pio_zajecia.lista_zajec)

In [ ]:
pio_zajecia.ile_mispow()

In [ ]:
print(pio_zajecia.lista_zajec)


In [ ]:
pio_zajecia

In [ ]:
print(pio_zajecia.ile_zajec)

In [ ]:
lista_zajec= [DzienZajec(lista_dzien, dzien) for lista_dzien, dzien in 
             zip(zajecia,dnityg)]

In [ ]:
print(lista_zajec)

In [ ]:
posortowane_po_zajeciach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_zajec)
posortowane_po_mispach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_mispow())

In [ ]:
print(posortowane_po_zajeciach)

In [ ]:
print(posortowane_po_mispach)

## Zadanie 1

Stworz typ NumerTelefonu

 -- przy tworzeniu sprawdza czy właściwy numer (Polski) jeśli nie pisze, że error (ew. Exception)
 
 -- gdy printuję to mi pisze polskimi słowami i.e. "jeden, pięć, siedem, zero"
 
 -- gdy wywołuję właściwość wojewodzwtwo, podaje mi wojewodztwo ew. ze to komorkowy
 
 

Stworzenie klasy o nazwie *NumerTelefonu*. Znajduje się w niej słownik województw, w którym do numerów kierunkowych przypisane są miasta.

In [ ]:
class NumerTelefonu():

  wojewodztwa_slownik = {"42":"Lodz", "32":"jakies miasto", "21":"inne miasto"}
  cyfry = ["zero", "jeden", "dwa", "trzy", "cztery", "pięć", "sześć", "siedem", "osiem", "dziewięć"]

#funkcja inicjalizacyjna
  def __init__(self, numer_telefonu): 
        self.numer = numer_telefonu
#funkcja sprawdzająca czy podany numer ma 9 znaków (oznacza wtedy, że jest to numer polski)
#jeśli tak jest wyświetla się komunikat "Numer poprawny"
#wykorzystywana jest zdefiniowana niżej funkcja ile_cyfr()
        if self.ile_cyfr() == 9:
          print("Numer poprawny")
        else:
          print("Numer niepoprawny")  
        
#Podanie z jakiego miasta jest numer
        self.wojewodztwo = "Numer jest sz miasta " + self.wojewodztwa_slownik[self.numer[:2]]

  def ile_cyfr(self):
        return len(self.numer)

#funkcja literująca i printująca podany numer
  def __repr__(self):
        return "".join(self.cyfry[int(cyfra)] + " " for cyfra in self.numer)


In [ ]:
numer = NumerTelefonu("423476789")

Numer poprawny


In [ ]:
print(numer)

cztery dwa trzy cztery siedem sześć siedem osiem dziewięć 


In [ ]:
numer.wojewodztwo

'Numer jest z miasta Lodz'